version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Initialize venv
          command: |
            python -m venv venv
            venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Linting
          command: |
            venv/bin/activate
            flake8

      - run:
          name: Run tests
          command: |
            venv/bin/activate
            pytest

workflows:
  main:
    jobs:
      - build-and-test
